version = "0.4.0"
content_dir = "content"

[html.spine]
vertebrae = ["**/*.typ"]

[html]
feed_base_url = "https://fanyingfx.github.io/blog"

[pdf.spine]
title = "rheo_project"
vertebrae = ["index.typ"]
merge = true

[epub.spine]
title = "rheo_project"
vertebrae = ["index.typ", "about.typ"]
